### ISSUE TITLE
Write LLVM commit hash and date into header of source files

### ISSUE THREAD

**Issue by Rot127** [rizinorg/rz-hexagon#38]
@thestr4ng3r suggested that it would be a nice idea to add the commit hash of LLVM, the date of the commit and a timestamp of generation somewhere in the source.
This way we could be easily seen how up to date the generated code is.

The information should be written as preamble (just like the license information) to all source files.

`Hexagon.json` unfortunately does not have this information. So those are the ways I can think of how to achieve this.

- Ask the user to give the commit hash and date to `LLVMImporter.py` as arguments. 
  - Easy but annoying for the user.
- Alter `llvm-tblgen` to include the commit hash and date into the generated json file.
  - Way more work, but less annoying for the user.
- Write commit hash into a file and update it every time a new `Hexagon.json` is used by hand.
  - Easy for the user who does not use a new `Hexagon.json`, but we should not forget to update it.

**Comment by thestr4ng3r** [comment]
Another option would be to let `LLVMImporter.py` call `llvm-tblgen` itself instead of having the user to do it beforehand. Then it can use `llvm-tblgen --version`. But that might also become annoying because the llvm source tree path is also needed.

**Comment by Rot127** [comment]
+1 for this idea. We could ask the user to set a environment variable with the path to the LLVM src. The existence of it could be checked each time `LLVMImporter.py` is run.

**Comment by Rot127** [comment]
Closed by https://github.com/rizinorg/rizin/pull/2180
